### ISSUE TITLE
Problem z kodem R cz.1

### ISSUE THREAD

**Issue by michalskrzypecki** [pbiecek/StatystykaII#81]
Dzień dobry.
Wstawiam taki kod do R:
> library(XML)
> library(RCurl)
> link <- "https://raw.githubusercontent.com/pbiecek/StatystykaII/master/MIMUW_2017/materialy/GlioblastomaWide.txt"
> xData <- getURL(link)
> tabele <- readHTMLTable(xData, stringsAsFactors = FALSE)

Pojawia się wtedy:

"Komunikat ostrzegawczy:
XML content does not seem to be XML: '"sampleID";"Cluster";"age";"death1y";"X..100133144";"X..100134869";"X..10357";" [...] "

Gdzie jest błąd w tym kodzie?
Uprzejmie proszę o pomoc w tej sprawie.
Michał Skrzypecki

**Comment by pbiecek** [comment]
Dane są zapisane w pliku tekstowym.
Należy je wczytać funkcją read.table() ustawiając ; jako separator.

**Comment by michalskrzypecki** [comment]
Dziękuję za odpowiedź.

Skorzystałem z funkcji read.table i otrzymałem następujące błędy:

> **read.table('GlioblastomaWide.rda', header=FALSE, sep=';')**

Błąd w poleceniu 'file(file, "rt")':nie można otworzyć połączenia
Dodatkowo: Komunikat ostrzegawczy:
W poleceniu 'file(file, "rt")':
  nie można otworzyć pliku 'GlioblastomaWide.rda': No such file or directory

> **read.table("GlioblastomaWide.rda", header=FALSE, sep='')**

Błąd w poleceniu 'file(file, "rt")':nie można otworzyć połączenia
Dodatkowo: Komunikat ostrzegawczy:
W poleceniu 'file(file, "rt")':
  nie można otworzyć pliku 'GlioblastomaWide.rda': No such file or directory

> **read.table(GlioblastomaWide.rda, header=FALSE, sep='')**

Błąd w poleceniu 'read.table(GlioblastomaWide.rda, header = FALSE, sep = "")':
  nie znaleziono obiektu 'GlioblastomaWide.rda'

Gdzie jest błąd?

Plik o nazwie GlioblastomaWide.rda mam zapisany na Pulpicie.

Michał Skrzypecki

**Comment by pbiecek** [comment]
@michalskrzypecki 
Poprzednio odczytywał pan plik GlioblastomaWide.txt, plik tekstowy odczytuje się poleceniem read.table()
plik binarny (a takim jest rda) można odczytać funkcją load()

Aby wczytać dane może pan użyć

dat <- read.table("https://raw.githubusercontent.com/pbiecek/StatystykaII/master/MIMUW_2017/materialy/GlioblastomaWide.txt", header=TRUE, sep=';')

U mnie ta linia działa poprawnie

**Comment by michalskrzypecki** [comment]
Dziękuję za odpowiedź.
