### ISSUE TITLE
Wstawianie na Github.

### ISSUE THREAD

**Issue by michalskrzypecki** [pbiecek/StatystykaII#97]
Dzień dobry, Panie Doktorze.
Chciałbym wstawić na Githuba poprawiony projekt.
Nie umiem jednak wstawić tego pliku na Github.
Jak to zrobić?

Uprzejmie proszę Pana o pomoc w tej sprawie.

Z wyrazami szacunku,
Michał Skrzypecki

**Comment by pbiecek** [comment]
Informacja o tym jak korzystać z GitHuba znajduje się tutaj:
http://pbiecek.github.io/Przewodnik/Programowanie/jak_korzystac_z_serwisu_github_i_waffle.html
jeżeli ten opis nie jest wystarczający, to zapraszam na konsultacje przed lub po zajeciach

**Comment by michalskrzypecki** [comment]
Dzień dobry, Panie Doktorze.
Bardzo dziękuję za odpowiedź.

Z wyrazami szacunku,
Michał Skrzypecki
